# Generated by Django 5.2 on 2025-05-07 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_comment_options_alter_comment_blog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comic_pages/')),
                ('page_number', models.PositiveIntegerField()),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='users.comic')),
            ],
            options={
                'ordering': ['page_number'],
            },
        ),
    ]
