# Generated by Django 5.2 on 2025-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='last_searched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
